version: "1.0"
info:
  model: int-scaffold
packages:
- name: Adapter_Ext_gitProject
  gitServerName: Adapters
  gitUrl: https://github.com/Sephali-Smrutisikha-IBM-1
  gitUsername: Sephali-Smrutisikha-IBM-1
  gitBranch: main
- name: WmJDBCAdapter
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
services:
- serviceName: project.adapter_ext_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:Database_ERT12
  packages:
  - name: Adapter_Ext_gitProject
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
configurationVariables:
  ? artConnection.Adapter_Ext_gitProject.project.adapter_ext_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_ERT12.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.Adapter_Ext_gitProject.project.adapter_ext_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_ERT12.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.Adapter_Ext_gitProject.project.adapter_ext_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_ERT12.connectionSettings.password
  : "{AES}gOk3wygfWVjWqDc4SLehnQ=="
  ? artConnection.Adapter_Ext_gitProject.project.adapter_ext_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_ERT12.connectionEnabled
  : "false"
  ? artConnection.Adapter_Ext_gitProject.project.adapter_ext_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_ERT12.connectionSettings.user
  : JDBC_BVT
  ? artConnection.Adapter_Ext_gitProject.project.adapter_ext_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_ERT12.connectionSettings.keyStore
  : ""
  ? artConnection.Adapter_Ext_gitProject.project.adapter_ext_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_ERT12.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.Adapter_Ext_gitProject.project.adapter_ext_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_ERT12.connectionSettings.serverName
  : adapter-oracle-121-on-amazonrds.cdmjexwbzoym.us-east-1.rds.amazonaws.com
  ? artConnection.Adapter_Ext_gitProject.project.adapter_ext_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_ERT12.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.Adapter_Ext_gitProject.project.adapter_ext_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_ERT12.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.Adapter_Ext_gitProject.project.adapter_ext_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_ERT12.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.Adapter_Ext_gitProject.project.adapter_ext_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_ERT12.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.Adapter_Ext_gitProject.project.adapter_ext_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_ERT12.connectionSettings.otherProperties
  : ""
  ? artConnection.Adapter_Ext_gitProject.project.adapter_ext_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_ERT12.connectionSettings.driverType
  : Progress® DataDirect®
  ? artConnection.Adapter_Ext_gitProject.project.adapter_ext_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_ERT12.connectionSettings.dbType
  : ORACLE
  ? artConnection.Adapter_Ext_gitProject.project.adapter_ext_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_ERT12.connectionSettings.trustStore
  : ""
  ? artConnection.Adapter_Ext_gitProject.project.adapter_ext_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_ERT12.connectionSettings.transactionType
  : LOCAL_TRANSACTION
  ? artConnection.Adapter_Ext_gitProject.project.adapter_ext_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_ERT12.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.oracle.OracleDataSource
  ? artConnection.Adapter_Ext_gitProject.project.adapter_ext_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_ERT12.connectionManagerSettings.poolable
  : "false"
  ? artConnection.Adapter_Ext_gitProject.project.adapter_ext_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_ERT12.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.Adapter_Ext_gitProject.project.adapter_ext_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_ERT12.connectionSettings.networkProtocol
  : ""
  ? artConnection.Adapter_Ext_gitProject.project.adapter_ext_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_ERT12.connectionSettings.portNumber
  : "1521"
  ? artConnection.Adapter_Ext_gitProject.project.adapter_ext_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_ERT12.connectionSettings.databaseName
  : ORCL
